### ISSUE TITLE
Add glu/glew submodules for ScummVM addon

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.sharkwouter.Minigalaxy#10]
ScummVM since 2.5.0 also needs these two submodules for games like The Longest Journey to work:
```
        "shared-modules/glu/glu-9.json",
        "shared-modules/glew/glew.json",
```

They should probably be [added](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/blob/master/addons/scummvm.json#L15) to the manifest if they are not included in the GNOME runtime.

**Comment by tim77** [comment]
https://github.com/flathub/io.github.sharkwouter.Minigalaxy/blob/master/modules/shared-modules.yml#L6

**Comment by AsciiWolf** [comment]
Oops! :-)

**Comment by tim77** [comment]
No prob. :) I also wanted to talk with you about maybe some reusable part of ScummVM manifest, just haven't enough time for all of this.

**Comment by AsciiWolf** [comment]
Feel free to reuse whatever part you want. :-)
