### ISSUE TITLE
Update to vervion 1.1.0

### ISSUE THREAD

**Issue by jntesteves** [flathub/io.github.sharkwouter.Minigalaxy#12]
Update to Minigalaxy version 1.1.0.

[https://github.com/sharkwouter/minigalaxy/releases/tag/1.1.0](https://github.com/sharkwouter/minigalaxy/releases/tag/1.1.0)

**Comment by tim77** [comment]
@jntesteves thanks for reporting. It's [updated](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/commit/08ce0d1dcb9f31f9ca98d05de05d4ebb64c3fb46) from day one. What we really need to do is update upstream appdata...
