### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by flukejones** [flathub/io.github.sharkwouter.Minigalaxy#13]
Seems v1.1.0 is available but flathub published version is v1.0.2

**Comment by tim77** [comment]
https://github.com/flathub/io.github.sharkwouter.Minigalaxy/issues/12#issuecomment-978361555

**Comment by tim77** [comment]
@flukejones but i'll try to submit upstream bump/update AppStream metainfo and remind @sharkwouter to bump it every time when new version released since this confusing users. Or you can help a little bit and submit this PR to upstream. :)

**Comment by flukejones** [comment]
Done https://github.com/sharkwouter/minigalaxy/pull/429

**Comment by sharkwouter** [comment]
@tim77 I made a branch so you can update without having all the recent additional changes which haven't been documented yet. Look at the 1.1.0-flathub branch.
