### ISSUE TITLE
Wine BaseApp

### ISSUE THREAD

**Issue by rowbawts** [flathub/io.github.sharkwouter.Minigalaxy#15]
I checked the referenced issue for the GitHub issue waiting for that Wine BaseApp to be merged for use with this Flatpak instead of relying on the Proton Steam extension and was pointed to [this](https://github.com/gasinvein/org.winehq.Wine) by the original PR author which might be useful for improving this Flatpak and potentially solving this issue.

**Comment by tim77** [comment]
@rowbawts hello. Please test Minigalaxy + Wine Flathub native build in [beta](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/tree/beta#minigalaxy-dev-version) branch. WARNING: old Proton prefixes will not work with Wine.
