### ISSUE TITLE
Savegames are lost after quitting Minigalaxy

### ISSUE THREAD

**Issue by lofidevops** [flathub/io.github.sharkwouter.Minigalaxy#19]
**Steps to reproduce:**

 1. Install Minigalaxy [via Flathub](https://flathub.org/apps/details/io.github.sharkwouter.Minigalaxy)
 2. Install and launch a game
 3. Use the savegame feature
 4. Quit the game
 5. Quit Minigalaxy
 6. Re-launch Minigalaxy
 7. Re-launch game
 8. Load savegame

**What should happen:**

 - The savegame is available to load.

**What happens instead:**

 - There are no savegames. As though the game was freshly installed.
 - Anguish.

**Footnotes:**

 - Confirmed with [Shadowrun Returns](https://www.gog.com/en/game/shadowrun_returns_deluxe_dlc) and  [Interrogation](https://www.gog.com/game/interrogation_you_will_be_deceived). I'm pretty sure I've played other games without encountering this problem.
 - If you quit the game, **do not** quit Minigalaxy, then launch the game again, the savegames appear as expected.
 - Info dumps (happy to provide more):

```
$ flatpak info io.github.sharkwouter.Minigalaxy

Minigalaxy - A simple GOG client for Linux

          ID: io.github.sharkwouter.Minigalaxy
         Ref: app/io.github.sharkwouter.Minigalaxy/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.1.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 556.5 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: b409e9a0a49c9bf471411090a6f3a9a0c6785bff265690655e84057eb8ce6032
      Parent: 1bdc0b12324946a790b3417ec0f762f1e6cf74b0a37dd8997410e22b24ef5aa2
     Subject: chore(update): modules (26c8b017)
        Date: 2022-05-15 00:28:22 +0000
```

```
$ flatpak info -M io.github.sharkwouter.Minigalaxy
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=all;
features=multiarch;
filesystems=~/GOG Games:create;

[Environment]
GST_PLUGIN_SYSTEM_PATH=/app/lib32/gstreamer-1.0:/app/lib/gstreamer-1.0:/usr/lib/i386-linux-gnu/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
WINEESYNC=1
WINEFSYNC=1
WINEDLLPATH=/app/dlls/lib32:/app/dlls/lib:/app/lib32/wine/wined3d:/app/lib/wine/wined3d
```

**Comment by lofidevops** [comment]
See https://github.com/sharkwouter/minigalaxy/issues/468 for another report, and confirmation from the Minigalaxy developer that this appears to be a flatpak issue.

**Comment by lofidevops** [comment]
This is an attempt to fix the problem https://github.com/flathub/io.github.sharkwouter.Minigalaxy/pull/5

**Comment by lofidevops** [comment]
@tim77 @sharkwouter Is there a standard way to solve this in the flatpak context? I'm guessing some coordination between application and packaging is required?

**Comment by sharkwouter** [comment]
It seems Shadowrun Returns saves in `~/.config`. Not sure about the other game.

**Comment by lofidevops** [comment]
Cannot reliably reproduce. Seems to be game specific.

**Comment by sharkwouter** [comment]
Yeah, in the end I do not maintain the flatpak version. Thanks for looking out for this issue, though.

**Comment by ArneBab** [comment]
I still get this for Divinity Original Sin: on every start I have to create a new profile, so no savegames are preserved. Can I do some trickery like symlinking a savegame path into ~/.config or such?

**Comment by tim77** [comment]
>  Can I do some trickery like symlinking a savegame path into ~/.config or such?

Symlinks will not work without additional tweaks. You can allow specific path for your game via [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) or via CLI [1]. It should be safe to allow strictly only necessary stuff for you game, Divinity in this case, so you need to allow `xdg-config/Divinity_data_location` directory. Try to avoid allowing whole `$HOME/.config`. 

[1]:
```bash
flatpak override --user --filesystem=xdg-config/Divinity_data_location
```

---

> Should this issue be resolved by the still open https://github.com/flathub/io.github.sharkwouter.Minigalaxy/pull/5 ? (if the attempt is rejected, should the PR be closed?)

We should close #5 since this is not a solution unfortunately and it could broke other games. We can't fix this without upstream game developers and patching games itself. Maybe we should document such workarounds in Wiki. Or maybe we can include all necessary paths into Minigalaxy Flathub build for all problematic games.

**Comment by ArneBab** [comment]
I tried the cli override, but it did not work (for divinity original sin). When I allow all of $HOME via flatseal, though, it actually finds old savegames from when I installed without minigalaxy (with horrible LD_LIBRARY_PATH hacks). How can I find out which paths a given game needs?

For your question: I think it would be ideal to include all necessary paths in Minigalaxy Flathub, because the biggest advantage of minigalaxy is that it just works: Select a game, click start and it runs. That’s just awesome, so it would be great if it worked for all games.

**Comment by Summertime** [comment]
> We should close #5 since this is not a solution unfortunately and it could broke other games.

I will note that implementing #5 has caused no additional issues for me, across multiple games and with Steam et al also installed.

It is the standard way to tell flatpak to retain all non-tmp files an app creates, without polluting the home directory et al.

**Comment by tim77** [comment]
> I will note that implementing https://github.com/flathub/io.github.sharkwouter.Minigalaxy/pull/5 has caused no additional issues for me, across multiple games and with Steam et al also installed.

Great, nice to hear that you tested it and there is no regressions!

> Trying to scrape data from [PCGamingWiki pages](https://www.pcgamingwiki.com/wiki/Darwinia) might be an option, but this would balloon the problem from what was a single line fix for the [Heroic](https://github.com/flathub/com.heroicgameslauncher.hgl/blob/9c673fd0e9a8260bdaf307bd516c29fa06e2ce5c/com.heroicgameslauncher.hgl.yml#L39) ([Commits](https://github.com/search?q=repo%3Aflathub%2Fcom.heroicgameslauncher.hgl+persist&type=commits)) and [Steam](https://github.com/flathub/com.valvesoftware.Steam/blob/4ff190217bbd6ee51d547671de367ba52dd28221/com.valvesoftware.Steam.yml#L41) ([Commits](https://github.com/search?q=repo%3Aflathub%2Fcom.valvesoftware.Steam+persist&type=commits)) flatpaks

Agree. Both Steam and HGL using it what surprised me. I mostly looked up on `flathub/net.lutris.Lutris` build and Lutris doesn’t using `--persist=.`.

After some discussions with other maintainers we could not come up with a real case where due of this option there could be a regression. I think we should try with `--persist=.` @Summertime thanks a lot! Going to merge your PR with this suggestion. Hope you will help with solving users issues if there any due this change. 😃
