### ISSUE TITLE
Game won't open; needs libopenal1 package

### ISSUE THREAD

**Issue by nathansgithub** [flathub/io.github.sharkwouter.Minigalaxy#7]
Hi,

I installed Dead Cells from inside Minigalaxy, but it gives me an error message when I try to run it. This is just using the Flatpak install. If I use a copy of Minigalaxy installed via apt, the game loads fine. Also, if I run the start.sh script in the game directory, it runs without any problems. 

I am running version 1.0.2 on Pop OS 21.04.

> flatpak run io.github.sharkwouter.Minigalaxy
Gtk-Message: 13:41:41.555: Failed to load module "appmenu-gtk-module"
Gtk-Message: 13:41:41.685: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 411, in set_proper_dlc_icon
    response = source.read_finish(async_res)
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 411, in set_proper_dlc_icon
    response = source.read_finish(async_res)
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 411, in set_proper_dlc_icon
    response = source.read_finish(async_res)
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
Failed to start Dead Cells:
Running Dead Cells
** ERROR ** Missing library libsndio.so.7.0
** ERROR ** Missing library libsndio.so.7.0
src/module.c(321) : FATAL ERROR : Failed to load library openal.hdll

**Comment by tim77** [comment]
Hi,

Sorry for so long respond. Problem not in OpenAL package since it available in runtime, but i've added few necessary modules and game should work now. Update will be published in few hours. Please reopen issue if the problem is still persist for you.
